#Use the new container-based infrastructure
sudo: false
language: sourcepawn
cache:
  directories:
    - .tmp

#Install some apt packages needed for spcomp
addons:
  apt_packages:
    - lib32stdc++6

#Webhooks
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c566d34b63ca82e43bbb
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

#Set the build environment
env:
  - SOURCEMOD=stable
  - SOURCEMOD=dev

# Allow dev build to fail
matrix:
  allow_failures:
    - env: SOURCEMOD=dev

#And compile!
script:
  - make compile-$SOURCEMOD
